//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllEmployeeDetails
    {
        public AllEmployeeDetails()
        {
            this.TR_EMPATTENDANCE = new HashSet<EmpAttendance>();
            this.TR_EMPLEAVE = new HashSet<EmployeeLeave>();
            this.TR_EMPLEAVE1 = new HashSet<EmployeeLeave>();
        }
    
        public int EmployeeID { get; set; }
        public int DepartmentId { get; set; }
        public int JobId { get; set; }
        public Nullable<int> EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> Mobile { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PersonalEmailId { get; set; }
        public int ReportingManager { get; set; }
        public int RoleId { get; set; }
    
        public virtual Department MT_DEPARTMENT { get; set; }
        public virtual ICollection<EmpAttendance> TR_EMPATTENDANCE { get; set; }
        public virtual JobDescription MT_JOBDESCRIPTION { get; set; }
        public virtual ICollection<EmployeeLeave> TR_EMPLEAVE { get; set; }
        public virtual ICollection<EmployeeLeave> TR_EMPLEAVE1 { get; set; }
    }
}
