//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAttendance
    {
        public int EMP_ID { get; set; }
        public int DEP_ID { get; set; }
        public int JOB_ID { get; set; }
        public Nullable<int> ATT_NUMOFDAYS { get; set; }
        public Nullable<int> ATT_TOTALWORKINGHRS { get; set; }
        public Nullable<System.DateTime> ATT_DATE { get; set; }
    
        public virtual Department MT_DEPARTMENT { get; set; }
        public virtual AllEmployeeDetails MT_EMPLOYEEDETAILS { get; set; }
        public virtual JobDescription MT_JOBDESCRIPTION { get; set; }
    }
}
