//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllEmployeeDetails 
    {
        public AllEmployeeDetails()
        {
            this.TR_EMPLEAVE = new HashSet<EmployeeLeave>();
            this.TR_EMPATTENDANCE = new HashSet<EmpAttendance>();
            this.TR_EMPLEAVE1 = new HashSet<EmployeeLeave>();
            this.MT_LEAVE = new HashSet<Leave>();
        }
    
        public int EMP_ID { get; set; }
        public int DEP_ID { get; set; }
        public int JOB_ID { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public string EMP_FIRSTNAME { get; set; }
        public string EMP_MIDDLENAME { get; set; }
        public string EMP_LASTNAME { get; set; }
        public string EMP_ADDRESS { get; set; }
        public string EMP_EMAIL { get; set; }
        public Nullable<int> EMP_MOBILENO { get; set; }
        public Nullable<int> EMP_PHONENO { get; set; }
        public Nullable<System.DateTime> EMP_JOININGDATE { get; set; }
        public string EMP_GENDER { get; set; }
        public Nullable<System.DateTime> EMP_DOB { get; set; }
        public string EMP_PERSONALMAILID { get; set; }
    
        public virtual Department MT_DEPARTMENT { get; set; }
        public virtual ICollection<EmployeeLeave> TR_EMPLEAVE { get; set; }
        public virtual ICollection<EmpAttendance> TR_EMPATTENDANCE { get; set; }
        public virtual ICollection<EmployeeLeave> TR_EMPLEAVE1 { get; set; }
        public virtual JobDescription MT_JOBDESCRIPTION { get; set; }
        public virtual ICollection<Leave> MT_LEAVE { get; set; }
    }
}
