//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public int EMP_ID { get; set; }
        public int DEP_ID { get; set; }
        public int JOB_ID { get; set; }
        public int LEAVE_ID { get; set; }
        public Nullable<int> LEAVE_REMAININGDAYS { get; set; }
        public string LEAVE_STATUS { get; set; }
        public int LEAVE_APPROVEDBY { get; set; }
        public string LEAVE_REASON { get; set; }
        public Nullable<System.DateTime> LEAVE_FROMDATE { get; set; }
        public Nullable<System.DateTime> LEAVE_TODATE { get; set; }
        public Nullable<System.DateTime> LEAVE_JOININGDATE { get; set; }
    
        public virtual Department MT_DEPARTMENT { get; set; }
        public virtual AllEmployeeDetails MT_EMPLOYEEDETAILS { get; set; }
        public virtual AllEmployeeDetails MT_EMPLOYEEDETAILS1 { get; set; }
        public virtual JobDescription MT_JOBDESCRIPTION { get; set; }
        public virtual Leave MT_LEAVE { get; set; }
    }
}
