//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public int EmployeeleaveID { get; set; }
        public int EmployeeId { get; set; }
        public int DepartmentId { get; set; }
        public int JobId { get; set; }
        public int LeaveId { get; set; }
        public Nullable<int> RemainingDays { get; set; }
        public Nullable<bool> LeaveApprovalStatus { get; set; }
        public string LeaveStatus { get; set; }
        public int LeaveApprovedBy { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<System.DateTime> LeaveFromdate { get; set; }
        public Nullable<System.DateTime> LeaveToDate { get; set; }
        public Nullable<System.DateTime> ReJoiningdate { get; set; }
        public Nullable<int> PaidLeave { get; set; }
        public Nullable<int> UnPaidLeave { get; set; }
        public Nullable<int> WeekendORHolidaysInLeave { get; set; }
        public Nullable<int> TotaldaysOnLeaveCurrent { get; set; }
        public Nullable<int> TotalLeaveTakenInYear { get; set; }
    
        public virtual Department MT_DEPARTMENT { get; set; }
        public virtual AllEmployeeDetails MT_EMPLOYEEDETAILS { get; set; }
        public virtual AllEmployeeDetails MT_EMPLOYEEDETAILS1 { get; set; }
        public virtual JobDescription MT_JOBDESCRIPTION { get; set; }
        public virtual Leave MT_LEAVE { get; set; }
        
    }
}
