//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public Leave()
        {
            this.TR_EMPLEAVE = new HashSet<EmployeeLeave>();
        }
    
        public int LEAVE_ID { get; set; }
        public string LEAVE_TYPE { get; set; }
        public int JOB_ID { get; set; }
        public string LEAVE_STATUS { get; set; }
        public Nullable<int> LEAVE_HOLIDAY { get; set; }
        public string LEAVE_WEEKOFF { get; set; }
        public int LEAVE_APPROVAL { get; set; }
        public Nullable<int> LEAVE_ONLEAVEDAYS { get; set; }
    
        public virtual AllEmployeeDetails MT_EMPLOYEEDETAILS { get; set; }
        public virtual JobDescription MT_JOBDESCRIPTION { get; set; }
        public virtual ICollection<EmployeeLeave> TR_EMPLEAVE { get; set; }
    }
}
