//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMSDBEntities : DbContext
    {
        public LMSDBEntities()
            : base("name=LMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<JobDescription> JobDescriptions { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<EmpAttendance> EmpAttendances { get; set; }
        public virtual DbSet<UserActivation> UserActivations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<AllEmployeeDetails> AllEmployeeDetails { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<EmployeeLeave> EmployeeLeaves { get; set; }
    }
}
